name: audience_network_example
description: Demonstrates how to use the audience_network plugin.
publish_to: "none"

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  audience_network:
    path: ../

flutter:
  uses-material-design: true
